language: go
sudo: true

matrix:
  include:
    - go: 1.4
    - go: 1.5
    - go: 1.6
    - go: tip

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libblkid-dev


script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet ./...
  - go test -v -race ./...
