language: go
sudo: true

matrix:
  include:
    - go: 1.4
    - go: 1.5
    - go: 1.6
    - go: tip

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libblkid-dev
  - go get golang.org/x/tools/cmd/vet


script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet ./slave ./master ./common/dtos ./common/wsserver
  - go test -v -race ./slave/ ./slave/osinterface ./common/dtos ./common/wsserver
